/**:
  ros__parameters:
    log_dir: /home/krb/ASRL/temp/steam_icp/simulation
    output_dir: /workspace/raid/krb/boreas/simulation
    root_path: /workspace/raid/krb/boreas
    sequence: "boreas-2021-09-02-11-42"
    lidar_config: "/home/krb/Documents/steam_icp/steam_icp/simulation/vls128_config.txt"
    num_threads: 20
    verbose: false
    imu_rate: 200.0
    offset_imu: 0.0025
    min_dist_sensor_center: 0.1
    max_dist_sensor_center: 200.0
    noisy_measurements: true
    sim_length: 20.0
    lidar_range_std: 0.02
    r_accel: [0.02, 0.02, 0.02]
    r_gyro: [0.01, 0.01, 0.01]
    gravity: -9.8042
    p0_bias: 0.01
    q_bias: 0.01
    qc_diag: [6.18047567e+04, 6.18047567e+04, 3.40402641e+03, 6.13821100e+01, 6.13821100e+01, 9.85316597e+03]
    ad_diag: [100.11439693, 100.11512779, 100.08909343, 100.07804446, 100.07103628, 100.11791258]
    x0: [0., 0., -2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.0, 0., 0., 0., 0., 0.0]
    accel_ramp_time: 0.3
    # x0: [0., 0., -2., 0., 0., 0., 0., 0., 0., 0., 0., 0., -0.5, 0., 0., 0., 0., -0.1]
    # x0: [0., 0., -2., -0.0197052, 0.0285345, 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.05.]
    walls: [-50., 50., -50., 50., 0., 10.]  # xmin, xmax, ymin, ymax, zmin, zmax
    sleep_delay: 0.0
    v_freqs : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    v_amps : [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    ax: 3.0
    biases: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05]  #b_ax, b_ay, b_az, b_wx, b_wy, b_wz
    pose_meas_trans_sigma: 0.025
    pose_meas_rot_sigma_degs: 0.5
    pose_rate: 1000.0
    xi_ig: [0., 0., 0.]
    # xi_ig: [-0.0197052, 0.0285345, 0.]